### ISSUE TITLE
App doesn't work on XFCE or older versions of GNOME

### ISSUE THREAD

**Issue by leandroramos** [flathub/org.gnome.Music#16]
GNOME Music does not open on Ubuntu 18.04 because of the old version of Tracker. To use on Ubuntu 18.04 (Tracker 2.0.3) I needed to install GNOME Music 3.32.
In other desktop environments, which do not include Tracker, the app also does not run. I tested on Fedora Silverblue with XFCE.

![image](https://user-images.githubusercontent.com/3253741/75052271-11544700-54ae-11ea-9252-c80257b05472.png)

In this excerpt from [manifest.json](https://github.com/flathub/org.gnome.Music/blob/a46167403cb7b725141ddaa386349c05e1f2f48b/org.gnome.Music.json#L62) the Tracker appears with its download URL. Should the Tracker come with GNOME Music?

All the best.

**Comment by FastOSlinux** [comment]
same error on openSUSE Leap KDE

**Comment by fosero** [comment]
No, Music uses the system Tracker, that is the part that indexes the content on disk.

There is currently not really a way to bundle Tracker inside the flatpak, hence the message. This will likely change in the future (with Tracker 3), but there is no fixed roadmap.

**Comment by leandroramos** [comment]
Thank you, @fosero. I'm closin this issue.
