### ISSUE TITLE
Update to 3.38

### ISSUE THREAD

**Issue by A6GibKm** [flathub/org.gnome.Music#23]
I have a work in progress at https://github.com/A6GibKm/org.gnome.Music, but I am not being able to build this. I am hitting the same issue they have at https://github.com/flathub/org.gnome.Lollypop/pull/101.

**Comment by bilelmoussaoui** [comment]
there's a patch you can copy from Lollypop to make gst-python build with fdo 20.08

**Comment by A6GibKm** [comment]
Thanks for dropping by, Ill send a PR in a bit, probably tomorrow for Hacktoberfest though.

**Comment by ptitjano** [comment]
PR Merged. Thank you @A6GibKm
